name: HelperBot
version: 3.0
main: me.Delocaz.HelperBot.HelperBot
author: Delocaz
commands:
    help:
        usage: /<command> <page>
    addhelp:
        usage: /<command> <page> <content>
    delhelp:
        usage: /<command> <page>